# Generated by Django 5.1.3 on 2024-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
