# Generated by Django 5.1.3 on 2024-12-14 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_food_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderDate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
