# Generated by Django 5.1.3 on 2024-12-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_order_discription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="discription",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
