# Generated by Django 5.1.3 on 2024-12-25 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_order_orderdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderfood",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_foods",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderfood",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ]
            ),
        ),
    ]
